### ISSUE TITLE
Mongodb extension failed to show database on Eclipse Che

### ISSUE THREAD

**Issue by abhsange** [mongodb-js/vscode#199]
I'm trying to use MongoDB extension(v0.2.1) on Eclipse Che (v 7.17.2) using VS Code compatibility feature. However it fails to start with following error 
```
Extension-Host:Could not load electron Cannot find module 'electron'
Require stack:
- /tmp/vscode-unpacked/mongodb.mongodb-vscode.latest.wtbjnmuwad.mongodb.mongodb-vscode-0.2.1.vsix/extension/dist/extension.js
- /home/theia/node_modules/@theia/plugin-ext/lib/hosted/node/plugin-host-rpc.js
- /home/theia/node_modules/@eclipse-che/theia-remote/lib/node/plugin-host-custom.js
Extension-Host:TypeError: e.modules.indexOf is not a function
    at Object.isEnterprise (/tmp/vscode-unpacked/mongodb.mongodb-vscode.latest.wtbjnmuwad.mongodb.mongodb-vscode-0.2.1.vsix/extension/dist/extension.js:246:337965)
    at /tmp/vscode-unpacked/mongodb.mongodb-vscode.latest.wtbjnmuwad.mongodb.mongodb-vscode-0.2.1.vsix/extension/dist/extension.js:246:300589
    at m (/tmp/vscode-unpacked/mongodb.mongodb-vscode.latest.wtbjnmuwad.mongodb.mongodb-vscode-0.2.1.vsix/extension/dist/extension.js:9:367615)
    at handleCallback (/tmp/vscode-unpacked/mongodb.mongodb-vscode.latest.wtbjnmuwad.mongodb.mongodb-vscode-0.2.1.vsix/extension/dist/extension.js:1:4736)
    at /tmp/vscode-unpacked/mongodb.mongodb-vscode.latest.wtbjnmuwad.mongodb.mongodb-vscode-0.2.1.vsix/extension/dist/extension.js:135:89596
    at /tmp/vscode-unpacked/mongodb.mongodb-vscode.latest.wtbjnmuwad.mongodb.mongodb-vscode-0.2.1.vsix/extension/dist/extension.js:234:266740
    at /tmp/vscode-unpacked/mongodb.mongodb-vscode.latest.wtbjnmuwad.mongodb.mongodb-vscode-0.2.1.vsix/extension/dist/extension.js:234:281186
    at /tmp/vscode-unpacked/mongodb.mongodb-vscode.latest.wtbjnmuwad.mongodb.mongodb-vscode-0.2.1.vsix/extension/dist/extension.js:234:275549
    at e.exports.<anonymous> (/tmp/vscode-unpacked/mongodb.mongodb-vscode.latest.wtbjnmuwad.mongodb.mongodb-vscode-0.2.1.vsix/extension/dist/extension.js:135:58498)
    at e.exports.emit (events.js:315:20)
Extension-Host:TypeError: r.databases.map is not a function
    at /tmp/vscode-unpacked/mongodb.mongodb-vscode.latest.wtbjnmuwad.mongodb.mongodb-vscode-0.2.1.vsix/extension/dist/extension.js:246:302820
    at m (/tmp/vscode-unpacked/mongodb.mongodb-vscode.latest.wtbjnmuwad.mongodb.mongodb-vscode-0.2.1.vsix/extension/dist/extension.js:9:367615)
    at handleCallback (/tmp/vscode-unpacked/mongodb.mongodb-vscode.latest.wtbjnmuwad.mongodb.mongodb-vscode-0.2.1.vsix/extension/dist/extension.js:1:4736)
    at /tmp/vscode-unpacked/mongodb.mongodb-vscode.latest.wtbjnmuwad.mongodb.mongodb-vscode-0.2.1.vsix/extension/dist/extension.js:135:89596
    at /tmp/vscode-unpacked/mongodb.mongodb-vscode.latest.wtbjnmuwad.mongodb.mongodb-vscode-0.2.1.vsix/extension/dist/extension.js:234:266740
    at /tmp/vscode-unpacked/mongodb.mongodb-vscode.latest.wtbjnmuwad.mongodb.mongodb-vscode-0.2.1.vsix/extension/dist/extension.js:234:281186
    at /tmp/vscode-unpacked/mongodb.mongodb-vscode.latest.wtbjnmuwad.mongodb.mongodb-vscode-0.2.1.vsix/extension/dist/extension.js:234:275549
    at e.exports.<anonymous> (/tmp/vscode-unpacked/mongodb.mongodb-vscode.latest.wtbjnmuwad.mongodb.mongodb-vscode-0.2.1.vsix/extension/dist/extension.js:135:58498)
    at e.exports.emit (events.js:315:20)
    at e (/tmp/vscode-unpacked/mongodb.mongodb-vscode.latest.wtbjnmuwad.mongodb.mongodb-vscode-0.2.1.vsix/extension/dist/extension.js:234:282308)
Extension-Host:No tree item with id 'b31524c7-c8ad-413e-8518-684b97592421-1604932875438' found.
```

Anything need to be included on Eclipse Che setup to make it work ?

**Comment by mmarcon** [comment]
Not sure what is happening there.

As we are focusing on making things work well in VS Code, this is not something that we are planning to look into in the near future so I am closing this issue.

I suggest creating a feature request in our [feedback portal](https://feedback.mongodb.com/forums/929236-mongodb-for-vs-code) so users and customers can vote for it and if it gets enough traction we will evaluate how to prioritize it.

Alternatively, you may consider troubleshooting it on your end and submit a PR with a fix.
