### ISSUE TITLE
Bug Report v1.8.0 Does Not Work

### ISSUE THREAD

**Issue by cwolter97** [mongodb-js/vscode#798]
#### Current Behavior

Mongo DB for VS Code does not start

```console
2024-08-29 20:00:39.444 [error] Activating extension mongodb.mongodb-vscode failed due to an error:
2024-08-29 20:00:39.444 [error] Error: Cannot find module 'electron'
Require stack:
- /home/node/.vscode-server/extensions/mongodb.mongodb-vscode-1.8.0/dist/extension.js
- /vscode/vscode-server/bin/linux-x64/fee1edb8d6d72a0ddff41e5f71a671c23ed924b9/out/bootstrap-fork.js
	at Module._resolveFilename (node:internal/modules/cjs/loader:1145:15)
	at Module._load (node:internal/modules/cjs/loader:986:27)
	at y._load (/vscode/vscode-server/bin/linux-x64/fee1edb8d6d72a0ddff41e5f71a671c23ed924b9/out/vs/workbench/api/node/extensionHostProcess.js:177:6051)
	at i._load (/vscode/vscode-server/bin/linux-x64/fee1edb8d6d72a0ddff41e5f71a671c23ed924b9/out/vs/workbench/api/node/extensionHostProcess.js:174:31787)
	at o._load (/vscode/vscode-server/bin/linux-x64/fee1edb8d6d72a0ddff41e5f71a671c23ed924b9/out/vs/workbench/api/node/extensionHostProcess.js:139:34334)
	at Module.require (node:internal/modules/cjs/loader:1233:19)
	at require (node:internal/modules/helpers:179:18)
	at 4482 (/home/node/.vscode-server/extensions/mongodb.mongodb-vscode-1.8.0/dist/extension.js:510:1753007)
	at u (/home/node/.vscode-server/extensions/mongodb.mongodb-vscode-1.8.0/dist/extension.js:510:3785018)
	at 3988 (/home/node/.vscode-server/extensions/mongodb.mongodb-vscode-1.8.0/dist/extension.js:489:4996462)
	at u (/home/node/.vscode-server/extensions/mongodb.mongodb-vscode-1.8.0/dist/extension.js:510:3785018)
	at 22587 (/home/node/.vscode-server/extensions/mongodb.mongodb-vscode-1.8.0/dist/extension.js:489:4993741)
	at u (/home/node/.vscode-server/extensions/mongodb.mongodb-vscode-1.8.0/dist/extension.js:510:3785018)
	at 38699 (/home/node/.vscode-server/extensions/mongodb.mongodb-vscode-1.8.0/dist/extension.js:489:4497890)
	at u (/home/node/.vscode-server/extensions/mongodb.mongodb-vscode-1.8.0/dist/extension.js:510:3785018)
	at 37617 (/home/node/.vscode-server/extensions/mongodb.mongodb-vscode-1.8.0/dist/extension.js:489:4472751)
	at u (/home/node/.vscode-server/extensions/mongodb.mongodb-vscode-1.8.0/dist/extension.js:510:3785018)
	at 13303 (/home/node/.vscode-server/extensions/mongodb.mongodb-vscode-1.8.0/dist/extension.js:489:5651882)
	at u (/home/node/.vscode-server/extensions/mongodb.mongodb-vscode-1.8.0/dist/extension.js:510:3785018)
	at 38813 (/home/node/.vscode-server/extensions/mongodb.mongodb-vscode-1.8.0/dist/extension.js:489:5601372)
	at u (/home/node/.vscode-server/extensions/mongodb.mongodb-vscode-1.8.0/dist/extension.js:510:3785018)
	at 53246 (/home/node/.vscode-server/extensions/mongodb.mongodb-vscode-1.8.0/dist/extension.js:489:5613623)
	at u (/home/node/.vscode-server/extensions/mongodb.mongodb-vscode-1.8.0/dist/extension.js:510:3785018)
	at 28288 (/home/node/.vscode-server/extensions/mongodb.mongodb-vscode-1.8.0/dist/extension.js:489:5604552)
	at u (/home/node/.vscode-server/extensions/mongodb.mongodb-vscode-1.8.0/dist/extension.js:510:3785018)
	at 10174 (/home/node/.vscode-server/extensions/mongodb.mongodb-vscode-1.8.0/dist/extension.js:489:5646324)
	at u (/home/node/.vscode-server/extensions/mongodb.mongodb-vscode-1.8.0/dist/extension.js:510:3785018)
	at 77225 (/home/node/.vscode-server/extensions/mongodb.mongodb-vscode-1.8.0/dist/extension.js:510:1032713)
	at u (/home/node/.vscode-server/extensions/mongodb.mongodb-vscode-1.8.0/dist/extension.js:510:3785018)
	at 36784 (/home/node/.vscode-server/extensions/mongodb.mongodb-vscode-1.8.0/dist/extension.js:510:1048412)
	at u (/home/node/.vscode-server/extensions/mongodb.mongodb-vscode-1.8.0/dist/extension.js:510:3785018)
	at 98783 (/home/node/.vscode-server/extensions/mongodb.mongodb-vscode-1.8.0/dist/extension.js:510:1170219)
	at u (/home/node/.vscode-server/extensions/mongodb.mongodb-vscode-1.8.0/dist/extension.js:510:3785018)
	at 64764 (/home/node/.vscode-server/extensions/mongodb.mongodb-vscode-1.8.0/dist/extension.js:510:1160092)
	at u (/home/node/.vscode-server/extensions/mongodb.mongodb-vscode-1.8.0/dist/extension.js:510:3785018)
	at /home/node/.vscode-server/extensions/mongodb.mongodb-vscode-1.8.0/dist/extension.js:510:3787463
	at Object.<anonymous> (/home/node/.vscode-server/extensions/mongodb.mongodb-vscode-1.8.0/dist/extension.js:510:3787571)
	at Module._compile (node:internal/modules/cjs/loader:1358:14)
	at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
	at Module.load (node:internal/modules/cjs/loader:1208:32)
	at Module._load (node:internal/modules/cjs/loader:1024:12)
	at y._load (/vscode/vscode-server/bin/linux-x64/fee1edb8d6d72a0ddff41e5f71a671c23ed924b9/out/vs/workbench/api/node/extensionHostProcess.js:177:6051)
	at i._load (/vscode/vscode-server/bin/linux-x64/fee1edb8d6d72a0ddff41e5f71a671c23ed924b9/out/vs/workbench/api/node/extensionHostProcess.js:174:31787)
	at o._load (/vscode/vscode-server/bin/linux-x64/fee1edb8d6d72a0ddff41e5f71a671c23ed924b9/out/vs/workbench/api/node/extensionHostProcess.js:139:34334)
	at Module.require (node:internal/modules/cjs/loader:1233:19)
	at require (node:internal/modules/helpers:179:18)
	at Function.i [as __$__nodeRequire] (/vscode/vscode-server/bin/linux-x64/fee1edb8d6d72a0ddff41e5f71a671c23ed924b9/out/bootstrap-fork.js:3:98)
	at m.xb (/vscode/vscode-server/bin/linux-x64/fee1edb8d6d72a0ddff41e5f71a671c23ed924b9/out/vs/workbench/api/node/extensionHostProcess.js:174:32966)
	at async Promise.all (index 0)
```

#### Code/Gist

n/a

#### Expected Behavior/Code

it runs

#### Environment

- node.js: v20.17.0
- pnpm: 8.6.1
- devcontainer: mcr.microsoft.com/vscode/devcontainers/javascript-node:0-20-bullseye
- host: Ubuntu 22.04.4 LTS
- local: Windows 10
- (win 10) vscode > connect to host (ubuntu) > open devcontainer (debian)

#### Possible Solution

Downgrade to v1.7.0

**Comment by shreyaskarnik** [comment]
+1 getting 
```javascript
Error running command mdb.addConnection: command 'mdb.addConnection' not found. This is likely caused by the extension that contributes mdb.addConnection.
``` 
the extension does not load

**Comment by alenakhineika** [comment]
Hey, thank you for reporting this! We are going to release a fix next week. In the meantime, if this blocks you and you need early access to the fix you can download and install the 1.8.1 version of the extension via [vsix from the pre-release](https://github.com/mongodb-js/vscode/releases/tag/untagged-ee46789398aad6df957f). Please let me know if this fixes the issue!

<img width="739" alt="vsix" src="https://github.com/user-attachments/assets/c8f381dc-97a8-4d06-9bbc-933da4205c24">

**Comment by eag-fbio** [comment]
Hi Alena, Most of us don't have that capability, nor can we downgrade to 1.7 because its autoupdate from the publisher.

**Comment by alenakhineika** [comment]
Got it. Please wait then for Monday when the fix is expected to be out. Sorry for the inconvenience!

**Comment by eag-fbio** [comment]
boy you are fast!  I was updating my comment.  I did figure a work around for how my config is.
Thank you for your concern!

**Comment by alenakhineika** [comment]
Hey, we just have shipped a follow-up v1.8.1 release with a bug fix. Please try it out and let us know if the extension now works for you.

**Comment by shreyaskarnik** [comment]
Works now thanks @alenakhineika

**Comment by alenakhineika** [comment]
Thank you for verifying! 🚀
