### ISSUE TITLE
Bug Report: Error connecting to mongodb atlas cluster in VSCode remote development environment

### ISSUE THREAD

**Issue by seanhxx** [mongodb-js/vscode#847]
#### Current Behavior

Error connecting to MongoDB Atlas Cluster in remote development environment, while working correctly in native environment

#### Environment

- VSCode: 1.93.1
- Host OS: Windows 11
- Remote OS: Ubuntu 24.04.1 LTS

#### VSCode Mongodb Extension Output

```
2024-09-30 07:04:38.942 [info] 2024-09-30T07:04:38.935Z explorer tree controller INFO  Connection tree item was expanded [
  {
    connectionId: 'a2c10c2d-3917-427a-9a9c-44ce8594f1bc',
    connectionName: 'cluster0.mcuis.mongodb.net',
    isExpanded: false
  }
]

2024-09-30 07:04:38.942 [info] 2024-09-30T07:04:38.935Z connection controller INFO  Connect called to connect to instance [ 'cluster0.mcuis.mongodb.net' ]

2024-09-30 07:04:38.942 [info] 2024-09-30T07:04:38.936Z connection controller INFO  Connecting to MongoDB... [
  {
    connectionInfo: '{"id":"a2c10c2d-3917-427a-9a9c-44ce8594f1bc","name":"cluster0.mcuis.mongodb.net","storageLocation":"GLOBAL","secretStorageLocation":"vscode.SecretStorage","connectionOptions":{"connectionString":"mongodb+srv://sfi-admin@cluster0.mcuis.mongodb.net/","useSystemCA":true,"oidc":{}}}'
  }
]

2024-09-30 07:04:38.942 [info] 2024-09-30T07:04:38.940Z connection controller INFO  COMPASS-DATA-SERVICE [
  { __value: 1001000014 },
  'Connection 1',
  'Connecting',
  {
    url: 'mongodb+srv://<credentials>@cluster0.mcuis.mongodb.net/?appName=mongodb-vscode',
    csfle: null
  }
]

2024-09-30 07:04:38.945 [info] 2024-09-30T07:04:38.943Z connection controller ERROR DEVTOOLS-CONNECT [
  { __value: 1000000041 },
  'compass-deps',
  'Missing optional dependency',
  {
    name: 'mongodb-client-encryption',
    error: "Cannot find module 'mongodb-client-encryption'\n" +
      'Require stack:\n' +
      '- /home/dev/.vscode-server/extensions/mongodb.mongodb-vscode-1.8.1/dist/extension.js\n' +
      '- /home/dev/.vscode-server/cli/servers/Stable-38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40/server/out/bootstrap-fork.js'
  }
]

2024-09-30 07:04:38.945 [info] 2024-09-30T07:04:38.944Z connection controller ERROR DEVTOOLS-CONNECT [
  { __value: 1000000041 },
  'compass-deps',
  'Missing optional dependency',
  {
    name: 'os-dns-native',
    error: "Cannot find module 'os-dns-native'\n" +
      'Require stack:\n' +
      '- /home/dev/.vscode-server/extensions/mongodb.mongodb-vscode-1.8.1/dist/extension.js\n' +
      '- /home/dev/.vscode-server/cli/servers/Stable-38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40/server/out/bootstrap-fork.js'
  }
]

2024-09-30 07:04:38.945 [info] 2024-09-30T07:04:38.944Z connection controller ERROR DEVTOOLS-CONNECT [
  { __value: 1000000041 },
  'compass-deps',
  'Missing optional dependency',
  {
    name: 'resolve-mongodb-srv',
    error: "Cannot find module 'resolve-mongodb-srv'"
  }
]

2024-09-30 07:04:38.949 [info] 2024-09-30T07:04:38.947Z connection controller INFO  DEVTOOLS-CONNECT [
  { __value: 1000000049 },
  'compass-connect',
  'Loaded system CA list',
  {
    caCount: 293,
    asyncFallbackError: undefined,
    systemCertsError: undefined
  }
]

2024-09-30 07:04:38.949 [info] 2024-09-30T07:04:38.949Z connection controller ERROR DEVTOOLS-CONNECT [
  { __value: 1000000038 },
  'compass-connect',
  'Resolving SRV record failed',
  {
    from: '',
    error: "Cannot find module 'resolve-mongodb-srv'",
    duringLoad: true,
    resolutionDetails: []
  }
]

2024-09-30 07:04:38.952 [info] 2024-09-30T07:04:38.952Z connection controller INFO  DEVTOOLS-CONNECT [
  { __value: 1000000042 },
  'compass-connect',
  'Initiating connection attempt',
  {
    uri: 'mongodb+srv://<credentials>@cluster0.mcuis.mongodb.net/?appName=mongodb-vscode',
    driver: { name: 'nodejs', version: '6.8.0' },
    devtoolsConnectVersion: '3.2.6',
    host: 'cluster0.mcuis.mongodb.net'
  }
]

2024-09-30 07:04:39.778 [info] 2024-09-30T07:04:39.566Z connection controller INFO  COMPASS-DATA-SERVICE [
  { __value: 1001000021 },
  'Connection 1',
  'Topology description changed',
  {
    isWritable: false,
    isMongos: false,
    previousType: 'Unknown',
    newType: 'ReplicaSetNoPrimary'
  }
]

2024-09-30 07:04:39.778 [info] 2024-09-30T07:04:39.566Z connection controller INFO  COMPASS-DATA-SERVICE [
  { __value: 1001000019 },
  'Connection 1',
  'Server opening',
  { address: 'cluster0-shard-00-00.mcuis.mongodb.net:27017' }
]

2024-09-30 07:04:39.778 [info] 2024-09-30T07:04:39.637Z connection controller INFO  COMPASS-DATA-SERVICE [
  { __value: 1001000019 },
  'Connection 1',
  'Server opening',
  { address: 'cluster0-shard-00-01.mcuis.mongodb.net:27017' }
]

2024-09-30 07:04:39.779 [info] 2024-09-30T07:04:39.707Z connection controller INFO  COMPASS-DATA-SERVICE [
  { __value: 1001000019 },
  'Connection 1',
  'Server opening',
  { address: 'cluster0-shard-00-02.mcuis.mongodb.net:27017' }
]

2024-09-30 07:04:39.780 [info] 2024-09-30T07:04:39.780Z connection controller WARN  COMPASS-DATA-SERVICE [
  { __value: 1001000023 },
  'Connection 1',
  'Server heartbeat failed',
  {
    connectionId: 'cluster0-shard-00-00.mcuis.mongodb.net:27017',
    duration: -1,
    failure: 'connect ECONNREFUSED 20.187.85.204:27017'
  }
]

2024-09-30 07:04:39.780 [info] 2024-09-30T07:04:39.780Z connection controller WARN  DEVTOOLS-CONNECT [
  { __value: 1000000034 },
  'compass-connect',
  'Server heartbeat failure',
  {
    connectionId: 'cluster0-shard-00-00.mcuis.mongodb.net:27017',
    failure: 'connect ECONNREFUSED 20.187.85.204:27017',
    isFailFast: true,
    isKnownServer: true
  }
]

2024-09-30 07:04:39.780 [info] 2024-09-30T07:04:39.780Z connection controller INFO  COMPASS-DATA-SERVICE [
  { __value: 1001000018 },
  'Connection 1',
  'Server description changed',
  {
    address: 'cluster0-shard-00-00.mcuis.mongodb.net:27017',
    error: 'connect ECONNREFUSED 20.187.85.204:27017',
    previousType: 'Unknown',
    newType: 'Unknown'
  }
]

2024-09-30 07:04:39.780 [info] 2024-09-30T07:04:39.780Z connection controller INFO  COMPASS-DATA-SERVICE [
  { __value: 1001000021 },
  'Connection 1',
  'Topology description changed',
  {
    isWritable: false,
    isMongos: false,
    previousType: 'ReplicaSetNoPrimary',
    newType: 'ReplicaSetNoPrimary'
  }
]

2024-09-30 07:04:39.781 [info] 2024-09-30T07:04:39.781Z connection controller WARN  COMPASS-DATA-SERVICE [
  { __value: 1001000023 },
  'Connection 1',
  'Server heartbeat failed',
  {
    connectionId: 'cluster0-shard-00-01.mcuis.mongodb.net:27017',
    duration: -1,
    failure: 'connect ECONNREFUSED 20.24.64.87:27017'
  }
]

2024-09-30 07:04:39.782 [info] 2024-09-30T07:04:39.781Z connection controller WARN  DEVTOOLS-CONNECT [
  { __value: 1000000034 },
  'compass-connect',
  'Server heartbeat failure',
  {
    connectionId: 'cluster0-shard-00-01.mcuis.mongodb.net:27017',
    failure: 'connect ECONNREFUSED 20.24.64.87:27017',
    isFailFast: true,
    isKnownServer: true
  }
]

2024-09-30 07:04:39.782 [info] 2024-09-30T07:04:39.781Z connection controller INFO  COMPASS-DATA-SERVICE [
  { __value: 1001000018 },
  'Connection 1',
  'Server description changed',
  {
    address: 'cluster0-shard-00-01.mcuis.mongodb.net:27017',
    error: 'connect ECONNREFUSED 20.24.64.87:27017',
    previousType: 'Unknown',
    newType: 'Unknown'
  }
]

2024-09-30 07:04:39.782 [info] 2024-09-30T07:04:39.781Z connection controller INFO  COMPASS-DATA-SERVICE [
  { __value: 1001000021 },
  'Connection 1',
  'Topology description changed',
  {
    isWritable: false,
    isMongos: false,
    previousType: 'ReplicaSetNoPrimary',
    newType: 'ReplicaSetNoPrimary'
  }
]

2024-09-30 07:04:39.784 [info] 2024-09-30T07:04:39.783Z connection controller WARN  COMPASS-DATA-SERVICE [
  { __value: 1001000023 },
  'Connection 1',
  'Server heartbeat failed',
  {
    connectionId: 'cluster0-shard-00-02.mcuis.mongodb.net:27017',
    duration: -1,
    failure: 'connect ECONNREFUSED 20.187.114.36:27017'
  }
]

2024-09-30 07:04:39.784 [info] 2024-09-30T07:04:39.784Z connection controller WARN  DEVTOOLS-CONNECT [
  { __value: 1000000034 },
  'compass-connect',
  'Server heartbeat failure',
  {
    connectionId: 'cluster0-shard-00-02.mcuis.mongodb.net:27017',
    failure: 'connect ECONNREFUSED 20.187.114.36:27017',
    isFailFast: true,
    isKnownServer: true
  }
]

2024-09-30 07:04:39.784 [info] 2024-09-30T07:04:39.784Z connection controller WARN  DEVTOOLS-CONNECT [
  { __value: 1000000036 },
  'compass-connect',
  'Aborting connection attempt as irrecoverable'
]

2024-09-30 07:04:39.785 [info] 2024-09-30T07:04:39.784Z connection controller INFO  COMPASS-DATA-SERVICE [
  { __value: 1001000018 },
  'Connection 1',
  'Server description changed',
  {
    address: 'cluster0-shard-00-02.mcuis.mongodb.net:27017',
    error: 'connect ECONNREFUSED 20.187.114.36:27017',
    previousType: 'Unknown',
    newType: 'Unknown'
  }
]

2024-09-30 07:04:39.785 [info] 2024-09-30T07:04:39.784Z connection controller INFO  COMPASS-DATA-SERVICE [
  { __value: 1001000021 },
  'Connection 1',
  'Topology description changed',
  {
    isWritable: false,
    isMongos: false,
    previousType: 'ReplicaSetNoPrimary',
    newType: 'ReplicaSetNoPrimary'
  }
]

2024-09-30 07:04:39.785 [info] 2024-09-30T07:04:39.784Z connection controller INFO  COMPASS-DATA-SERVICE [
  { __value: 1001000020 },
  'Connection 1',
  'Server closed',
  { address: 'cluster0-shard-00-00.mcuis.mongodb.net:27017' }
]

2024-09-30 07:04:39.785 [info] 2024-09-30T07:04:39.784Z connection controller INFO  COMPASS-DATA-SERVICE [
  { __value: 1001000020 },
  'Connection 1',
  'Server closed',
  { address: 'cluster0-shard-00-01.mcuis.mongodb.net:27017' }
]

2024-09-30 07:04:39.785 [info] 2024-09-30T07:04:39.784Z connection controller INFO  COMPASS-DATA-SERVICE [
  { __value: 1001000020 },
  'Connection 1',
  'Server closed',
  { address: 'cluster0-shard-00-02.mcuis.mongodb.net:27017' }
]

2024-09-30 07:04:39.785 [info] 2024-09-30T07:04:39.785Z connection controller INFO  COMPASS-DATA-SERVICE [ { __value: 1001000315 }, 'Connection 1', 'Client is closed' ]

2024-09-30 07:04:39.785 [info] 2024-09-30T07:04:39.785Z connection controller INFO  DEVTOOLS-CONNECT [
  { __value: 1000000037 },
  'compass-connect',
  'Connection attempt finished',
  undefined
]

2024-09-30 07:04:39.786 [info] 2024-09-30T07:04:39.786Z connection controller DEBUG Connection Attempt [
  { __value: 1001000279 },
  'connect',
  'connection attempt failed',
  MongoNetworkError: connect ECONNREFUSED 20.187.85.204:27017
      at C (/home/dev/.vscode-server/extensions/mongodb.mongodb-vscode-1.8.1/dist/extension.js:489:5814879)
      at TLSSocket.<anonymous> (/home/dev/.vscode-server/extensions/mongodb.mongodb-vscode-1.8.1/dist/extension.js:489:5813982)
      at Object.onceWrapper (node:events:634:26)
      at TLSSocket.emit (node:events:519:28)
      at TLSSocket.emit (node:domain:488:12)
      at emitErrorNT (node:internal/streams/destroy:169:8)
      at emitErrorCloseNT (node:internal/streams/destroy:128:3)
      at processTicksAndRejections (node:internal/process/task_queues:82:21) {
    [Symbol(errorLabels)]: Set(1) { 'ResetPool' },
    [cause]: Error: connect ECONNREFUSED 20.187.85.204:27017
        at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1606:16) {
      errno: -111,
      code: 'ECONNREFUSED',
      syscall: 'connect',
      address: '20.187.85.204',
      port: 27017
    }
  }
]

2024-09-30 07:04:39.786 [info] 2024-09-30T07:04:39.786Z connection controller ERROR Failed to connect by a connection id [
  MongoNetworkError: connect ECONNREFUSED 20.187.85.204:27017
      at C (/home/dev/.vscode-server/extensions/mongodb.mongodb-vscode-1.8.1/dist/extension.js:489:5814879)
      at TLSSocket.<anonymous> (/home/dev/.vscode-server/extensions/mongodb.mongodb-vscode-1.8.1/dist/extension.js:489:5813982)
      at Object.onceWrapper (node:events:634:26)
      at TLSSocket.emit (node:events:519:28)
      at TLSSocket.emit (node:domain:488:12)
      at emitErrorNT (node:internal/streams/destroy:169:8)
      at emitErrorCloseNT (node:internal/streams/destroy:128:3)
      at processTicksAndRejections (node:internal/process/task_queues:82:21) {
    [Symbol(errorLabels)]: Set(1) { 'ResetPool' },
    [cause]: Error: connect ECONNREFUSED 20.187.85.204:27017
        at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1606:16) {
      errno: -111,
      code: 'ECONNREFUSED',
      syscall: 'connect',
      address: '20.187.85.204',
      port: 27017
    }
  }
]
```

**Comment by Anemy** [comment]
Hi @seanhxx - Thanks for the logs, a few questions to help us understand the issue:
Thanks for the logs, looks like it could be a connectivity issue.
Do you have an ip access list setup for your Atlas cluster?
https://www.mongodb.com/docs/atlas/security/ip-access-list/#std-label-access-list
Maybe you need to add an entry for the remote environment?

If you install the MongoDB shell, mongosh, on the remote environment, are you able to connect with it?
https://www.mongodb.com/docs/mongodb-shell/ 

Is there any specific network setup on the remote environment?

**Comment by seanhxx** [comment]
Thanks for the reply. I tried for the mongodb shell and it shows the same error. I see that the problem is probably because of network configuration instead of the vscode addon.
