### ISSUE TITLE
Playground through SSH connection?

### ISSUE THREAD

**Issue by Jule-** [mongodb-js/vscode#97]
Hi,

I succeed to connect to my MongoDB instance through SSH connection, I can see all my collections in the left panel.

But when I try to get playground completion or even playground running my code I get `connection timed out`:
```
MONGOSH get list collections error: MongoServerSelectionError: connection timed out
    at Timeout._onTimeout (~/.vscode/extensions/mongodb.mongodb-vscode-0.0.2/dist/languageServerWorker.js:2028:270924)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
```

The documentation does not mention any restriction for playground or even mongo shell access. Am I doing something wrong or is it a bug?

**Comment by Anemy** [comment]
Thanks Jule-
We've looked into this and it's a bug with how our language server which runs playgrounds is handling ssh configurations on connections.  I'll message here once we've got a fix in progress/pushed :)
Thanks for bringing it up and helping us improve the extension.

**Comment by Jule-** [comment]
Hi @Anemy,
You are welcome, really happy to help! Thank you for this promising project, I am looking forward to see where this project can go! :slightly_smiling_face:

**Comment by Anemy** [comment]
@Jule- We've just pushed the new version now - let us know how it goes. Feel free to reopen if the issue hasn't gone away.

**Comment by Jule-** [comment]
@Anemy All seems to work fine in Playground as far as I could have tested! Good job! 👍 
✅ Playground Completion
✅ Playground Running

On the other hand the `MongoDB: Launch MongoDB Shell` is not working, I guess because you planned it only for local server, am I right?
```
$ mongo $MDB_CONNECTION_STRING; unset MDB_CONNECTION_STRING
MongoDB shell version v4.2.0
connecting to: mongodb://127.0.0.1:29282/?appname=mongodb-vscode%200.0.3&authSource=public&compressors=disabled&gssapiServiceName=mongodb&readPreference=primary&ssl=true
2020-05-27T09:12:13.949+0200 E  NETWORK  [js] SSL peer certificate validation failed: Certificate trust failure: CSSMERR_TP_NOT_TRUSTED; connection rejected
2020-05-27T09:12:13.949+0200 E  QUERY    [js] Error: couldn't connect to server 127.0.0.1:29282, connection attempt failed: SSLHandshakeFailed: SSL peer certificate validation failed: Certificate trust failure: CSSMERR_TP_NOT_TRUSTED; connection rejected :
connect@src/mongo/shell/mongo.js:341:17
@(connect):2:6
2020-05-27T09:12:13.951+0200 F  -        [main] exception: connect failed
2020-05-27T09:12:13.951+0200 E  -        [main] exiting with code 1
```
It is not a big deal because it is pretty easy to ssh on my server in order to run it but it could be pretty nice to have this shortcut working with our current DB connections. 🙂 

Thanks again, I think I will use this extension quite often! 😉

**Comment by Jule-** [comment]
I have just seen #120, maybe I have my answer! 🙂
